remote_theme: pmarsceill/just-the-docs

title: Matt DiPietro
description: "a brief guide to me as a co-worker, manager, and employee"

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/profile-picture.png"

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "&copy; 2021 Matthew DiPietro."

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
